### ISSUE TITLE
redis冲突

### ISSUE THREAD

**Issue by zhengweis** [zhangxd1989/springboot-dubbox#1]
dubbox 换成redis 注册中心，jar冲突  
=。 =
@zhangxd1989

**Comment by Brania** [comment]
启动ClientMobileApplication为什么出现如下编译错误无法启动：
Error:java: Internal compiler error: java.lang.Exception: java.lang.IllegalStateException: Failed to write metadata at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)

**Comment by zhangxd1989** [comment]
Jedis的确会有冲突，高版本依赖了common.pool2,低版本依赖的是common.pool，导致无法向下兼容，可以考虑升级dubbox中的Jedis版本，建议还是使用zookeeper作为服务注册中心

**Comment by zhengweis** [comment]
是的，只能重新修改dubbox2.8.4支持pool2了。
生产环境用的东西有点多 zookeeper、redis。。。看着有点难受 =。 =
