### ISSUE TITLE
ClientMobileApplication启动编译错误

### ISSUE THREAD

**Issue by Brania** [zhangxd1989/springboot-dubbox#2]
Error:java: Internal compiler error: java.lang.Exception: java.lang.IllegalStateException: Failed to write metadata at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)

**Comment by zhangxd1989** [comment]
没有复现这个问题，看异常是写metadata时eclipse的问题，项目中与metadata相关的依赖spring-boot-configuration-processor，可以注释掉调试下，或者给我提供更多的信息

**Comment by Brania** [comment]
谢谢，删除本地项目重新pull之后就没问题咯。
