### ISSUE TITLE
具体环境可以描述一下吗

### ISSUE THREAD

**Issue by lqq-cb** [zhangxd1989/springboot-dubbox#4]
比如jdk版本，mevn插件版本，redis版本等信息，我把你的项目clone下来，你的pom.xml里面的依赖dubbo版本是2.8.4，我down不了这个jar，我改成了2.5.3就没有pom文件报错了，但是java代码报错了。应该没有哪些方法，所以麻烦i描述一下。不然我永远本地跑不起来啊。谢谢。

**Comment by zhangxd1989** [comment]
java 1.8（有用到1.8的特性，pom文件有指明）
maven 3.2+（Spring boot maven插件要求 http://docs.spring.io/spring-boot/docs/1.3.8.RELEASE/reference/htmlsingle/#getting-started-system-requirements）
redis 没有用高版本特性，对版本没有要求，我用的3.2
dubbo用的是当当改造的dubbox2.8.4(pom中配置的私服是有这个jar的)
